language: ruby
cache: bundler
rvm:
- 2.1
addons:
  ssh_known_hosts: engnroom.org
before_install:
- openssl aes-256-cbc -K $encrypted_5abeaa89f416_key -iv $encrypted_5abeaa89f416_iv
  -in deploy-key-library.enc -out deploy-key-library -d
- chmod 600 ~/.ssh/config
- chmod 600 deploy-key-library
- mv deploy-key-library ~/.ssh/id_rsa
- rm deploy-key-library.enc
- echo -e "Host engnroom.org" >> ~/.ssh/config
- echo -e "IdentityFile ~/.ssh/id_rsa" >> ~/.ssh/config
before_script:
- bash script/install.sh
script:
- bash script/build.sh
after_success:
- bash script/deploy.sh
branches:
  only:
  - gh-pages
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
